# ai_engine/incident_worker.py
import os
import json
import redis
from agents.orchestrator import incident_ai_graph

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")
INCIDENT_QUEUE = 'neuralops:incidents:queue'

def start_incident_worker():
    print(f"🚀 AI Agent Orchestrator Listening on {INCIDENT_QUEUE}...")
    client = redis.Redis.from_url(REDIS_URL, decode_responses=True)

    while True:
        try:
            # Block until an anomaly payload pops out of the sliding window pipeline
            result = client.blpop(INCIDENT_QUEUE, timeout=0)
            if not result:
                continue
                
            _, raw_payload = result
            trigger_data = json.loads(raw_payload)
            
            print(f"\n🚨 [Incident Worker] Initializing AI Task Force for Service: {trigger_data['serviceId']}")

            # 1. Initialize the State object with our seed trigger telemetry
            initial_state = {
                "service_id": trigger_data["serviceId"],
                "trigger_event_id": trigger_data["triggerEventId"],
                "reason": trigger_data["reason"],
                "context_logs": [],
                "similar_past_incidents": [],
                "root_cause_analysis": "",
                "remediation_plan": [],
                "investigation_complete": False
            }

            # 2. Invoke the compiled LangGraph execution chain

            # 3. Log out the diagnostic summary generated by the unified agent fleet
            final_state = incident_ai_graph.invoke(initial_state)

            print("🏁 INVESTIGATION COMPLETE. Broadcasting via Pub/Sub...")
            
            # Use the existing Redis client to publish the result back to Node.js
            client.publish('neuralops:alerts', json.dumps(final_state))
            
            # ... rest of the logging ...
            
        except Exception as e:
            print(f"❌ Incident Worker Exception: {e}")
        

if __name__ == "__main__":
    start_incident_worker()